/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        LibraryTest classUnderTest = new LibraryTest();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.testSomeLibraryMethod());
    }
}
